version: '3.8'

# Development overrides
services:
  backend:
    build:
      target: runtime
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=true
      - DOTNET_RUNNING_IN_CONTAINER=true
    volumes:
      - ./backend:/app/source:ro
    command: ["dotnet", "watch", "run", "--project", "/app/source", "--urls", "http://0.0.0.0:8080"]

  frontend:
    build:
      target: development
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app:cached
      - node_modules:/app/node_modules

volumes:
  node_modules:
