app = "voxmed-app"

primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  ASPNETCORE_URLS = "http://+:8080"
  VITE_API_BASE_URL = "http://localhost:8080"
  VITE_AUTH_ENDPOINT = "/api/auth/login"
  VITE_APP_NAME = "VoxMed"
  # Adicione outras variáveis de ambiente conforme necessário

[[services]]
  internal_port = 8080
  protocol = "tcp"
  processes = ["app"]

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
