services:
  - type: web
    name: voxmed-backend
    env: docker
    plan: free
    dockerfilePath: backend/Dockerfile
    autoDeploy: true
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Development
      - key: ASPNETCORE_URLS
        value: http://+:8080;https://+:8081
      - key: ASPNETCORE_HTTPS_PORTS
        value: 8081
      - key: ConnectionStrings__DefaultConnection
        value: Host=ep-cold-band-aeafaabt-pooler.c-2.us-east-2.aws.neon.tech;Port=5432;Database=neondb;Username=neondb_owner;Password=npg_mvn8FaLJWlz5;SslMode=Require;ChannelBinding=Require
      - key: JwtSettings__SecretKey
        value: VoxMedAuthenticationSecretKeyForJWTTokenGeneration123456789
      - key: JwtSettings__Issuer
        value: VoxMedAPI
      - key: JwtSettings__Audience
        value: VoxMedApp
      - key: JwtSettings__ExpirationInHours
        value: 24
  # Render does not support 'ports' or 'dependsOn' fields

  - type: web
    name: voxmed-frontend
    env: docker
    plan: free
    dockerfilePath: frontend/Dockerfile
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: development
      - key: VITE_API_BASE_URL
        value: http://voxmed-backend:8080
      - key: VITE_AUTH_ENDPOINT
        value: /api/auth/login
      - key: VITE_APP_NAME
        value: VoxMed
  # Render does not support 'ports' or 'dependsOn' fields

  # - type: pserv
  #   name: voxmed-database
  #   env: docker
  #   plan: free
  #   dockerfilePath: database/Dockerfile
  #   autoDeploy: true
  #   envVars:
  #     - key: POSTGRES_DB
  #       value: voxmeddb
  #     - key: POSTGRES_USER
  #       value: voxmed
  #     - key: POSTGRES_PASSWORD
  #       value: VoxMed@2025!
  #     - key: PGDATA
  #       value: /var/lib/postgresql/data/pgdata
  # Render does not support 'ports' field
  # Disk removed for free tier compatibility
  # healthCheckPath removed for pserv compatibility
