# fly.toml app configuration file generated for backend-delicate-wave-8071 on 2025-08-29T03:12:41-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backend-delicate-wave-8071'
primary_region = 'gig'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
